### ISSUE TITLE
meta: starting update to Proposal #9

### ISSUE THREAD

**Issue by tunnckoCore** [Zimtente/ens-collections#188]
@CryptoGatsu, please stop merging until tomorrow cuz there will be changes, and this will just cause more merge conflicts.

- I'll setup CI/CD pipelines
- Issue templates
- add labels for each category
- token generation and adjusting to the proposed format in #9 

From forced non-blank issues, e.g. when you have issue templates, we can detect what issue template is opened from CI/workflows and parsed the body for names or etc and generate the rest of the stuff.

**Comment by tunnckoCore** [comment]
@Zimtente should we really use `idna-uts46-hx`? I don't see anything about it in the ENS docs.

Plus, there seems to be a problem converting `!?` double emoji

```
Error: Illegal char ⁉
    at mapLabel (/home/sigma/dev/opensource/node_modules/idna-uts46-hx/uts46.js:29:11)
    at process (/home/sigma/dev/opensource/node_modules/idna-uts46-hx/uts46.js:49:22)

```

**Comment by tunnckoCore** [comment]
Yea.. seems like `ensjs` v3 uses [`eth-ens-namehash`](https://github.com/danfinlay/eth-ens-namehash) which is using `uts46.toAscii(name, {useStd3ASCII: true, transitional: false})` and not our current default `uts46.toUnicode(name, {useStd3ASCII: true})`

I'm switching to it.

**Comment by tunnckoCore** [comment]
How's that even in the collection.. `⁉️⁉️`

It's invalid domain even as per the `ens.domains` register.

![image](https://user-images.githubusercontent.com/5038030/177709150-186a00f6-6ef4-43c6-b186-c4461ad32d46.png)

**Comment by tunnckoCore** [comment]
Double `‼️‼️` too
